"""Shared fixtures of the Chastre tests. Nothing here was run by its author (file-only tools); Codex records results.

The synthetic terrain is tiny (a 10 x 8 interior inside a nodata ring) so that actual MAPLE tiles are compiled in seconds; the
real 33 GB case is never generated by a test."""
import hashlib
import shutil
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[2]
for sub in ("tests/phase4", "tests/phase4s", "tests/hydraulic_candidates", "tests", "benchmarks/rfid",
            "benchmarks/hydraulic_candidates", "benchmarks/newton_cpu", "tests/rfid", "tests/chastre"):
    sys.path.insert(0, str(ROOT / sub))

from chastre_helpers import (
    NX,
    NY,
    recipe_dict,
    synthetic_interior,
    write_dtm,
)

RFID_RECIPE = ROOT / "cases" / "rfid" / "recipe.yaml"
N_ACTIVE, N_SINKS = NY * NX - 2, 5


@pytest.fixture(scope="session")
def gpu():
    backend = pytest.importorskip("maple.core.backend")
    if not backend.gpu_execution_available():
        pytest.skip("CuPy or a CUDA device is unavailable; the CUDA paths are not exercised")
    return backend.cupy_module()


@pytest.fixture(scope="session")
def rfid_source(tmp_path_factory):
    """A generated, compiled and verified (synthetic-capture) RFID case: the source the Chastre case pins."""
    pytest.importorskip("maple")
    pytest.importorskip("yaml")
    from rfid_helpers import RFID_INPUT, synthetic_capture

    from maple_syrup.rfid_case import (
        generate_rfid_case,
        load_rfid_recipe,
        verify_rfid_case,
    )

    if not (RFID_INPUT / "mahleran_input.xml").is_file():
        pytest.skip("MAHLERAN RFID_2014 input not available")
    base = tmp_path_factory.mktemp("chastre_rfid_source")
    capture = base / "syrup_hydro_steps.txt"
    capture.write_text(synthetic_capture())
    digest = hashlib.sha256(synthetic_capture().encode("ascii")).hexdigest()
    real = load_rfid_recipe(RFID_RECIPE).raw["forcing"]["capture_expected_sha256"]
    recipe_path = base / "recipe" / "recipe.yaml"  # NOT beside the output: generation refuses to write inside the recipe tree
    recipe_path.parent.mkdir()
    recipe_path.write_text(RFID_RECIPE.read_text().replace(real, digest))
    out = base / "case"
    generate_rfid_case(load_rfid_recipe(recipe_path), out, applied_forcing_capture=capture)
    return verify_rfid_case(out, allow_maple_source_change=True)


@pytest.fixture(scope="session")
def dtm_path(tmp_path_factory):
    path = tmp_path_factory.mktemp("chastre_dtm") / "dtm.asc"
    write_dtm(path, synthetic_interior())
    return path


@pytest.fixture(scope="session")
def synthetic_recipe_file(rfid_source, dtm_path, tmp_path_factory):
    import yaml

    from maple_syrup.chastre_case import load_chastre_recipe, plan_only

    base = tmp_path_factory.mktemp("chastre_recipe")
    path = base / "recipe" / "recipe.yaml"
    path.parent.mkdir()
    # nz is only known from the bed plan: read it from the (write-nothing) plan with a placeholder expectation
    path.write_text(yaml.safe_dump(recipe_dict(dtm_path, rfid_source.case_dir, n_active=N_ACTIVE, n_sinks=N_SINKS, nz=1)))
    nz = plan_only(load_chastre_recipe(path), base / "never_written")["nz"]
    path.write_text(yaml.safe_dump(recipe_dict(dtm_path, rfid_source.case_dir, n_active=N_ACTIVE, n_sinks=N_SINKS, nz=nz)))
    return path


@pytest.fixture(scope="session")
def chastre_case_dir(rfid_source, synthetic_recipe_file, tmp_path_factory):
    """A generated tiled synthetic case (4-row bands: 4, 4, 2 rows)."""
    from maple_syrup.chastre_case import generate_chastre_case, load_chastre_recipe

    out = tmp_path_factory.mktemp("chastre_generated") / "case"
    generate_chastre_case(load_chastre_recipe(synthetic_recipe_file), out, source_case_dir=rfid_source.case_dir,
                          allow_maple_source_change=True)
    return out


@pytest.fixture()
def case_copy(chastre_case_dir, tmp_path):
    """A private copy of the generated case that a test may tamper with."""
    target = tmp_path / "case"
    shutil.copytree(chastre_case_dir, target)
    return target
